import { MaterialCommunityIcons } from "@expo/vector-icons";

export const SPLIT_ICON_MAP: Record<string, { icon: keyof typeof MaterialCommunityIcons.glyphMap; iconColor: string; iconBg: string }> = {
  electricity: { icon: "flash-outline", iconColor: "#3b82f6", iconBg: "#dbeafe" },
  electric: { icon: "flash-outline", iconColor: "#3b82f6", iconBg: "#dbeafe" },
  power: { icon: "flash-outline", iconColor: "#3b82f6", iconBg: "#dbeafe" },
  water: { icon: "water-outline", iconColor: "#06b6d4", iconBg: "#ccfbf1" },
  transportation: { icon: "bus", iconColor: "#ca8a04", iconBg: "#fef9c3" },
  transport: { icon: "bus", iconColor: "#ca8a04", iconBg: "#fef9c3" },
  bus: { icon: "bus", iconColor: "#ca8a04", iconBg: "#fef9c3" },
  taxi: { icon: "taxi", iconColor: "#ca8a04", iconBg: "#fef9c3" },
  uber: { icon: "car", iconColor: "#ca8a04", iconBg: "#fef9c3" },
  food: { icon: "food-outline", iconColor: "#ea580c", iconBg: "#ffedd5" },
  meal: { icon: "food-outline", iconColor: "#ea580c", iconBg: "#ffedd5" },
  dinner: { icon: "food-outline", iconColor: "#ea580c", iconBg: "#ffedd5" },
  lunch: { icon: "food-outline", iconColor: "#ea580c", iconBg: "#ffedd5" },
  breakfast: { icon: "food-outline", iconColor: "#ea580c", iconBg: "#ffedd5" },
  rent: { icon: "home-outline", iconColor: "#7c3aed", iconBg: "#ede9fe" },
  housing: { icon: "home-outline", iconColor: "#7c3aed", iconBg: "#ede9fe" },
  accommodation: { icon: "home-outline", iconColor: "#7c3aed", iconBg: "#ede9fe" },
  internet: { icon: "wifi", iconColor: "#0ea5e9", iconBg: "#e0f2fe" },
  wifi: { icon: "wifi", iconColor: "#0ea5e9", iconBg: "#e0f2fe" },
  phone: { icon: "phone-outline", iconColor: "#8b5cf6", iconBg: "#f3e8ff" },
  mobile: { icon: "phone-outline", iconColor: "#8b5cf6", iconBg: "#f3e8ff" },
  data: { icon: "database", iconColor: "#8b5cf6", iconBg: "#f3e8ff" },
  gas: { icon: "fire", iconColor: "#f97316", iconBg: "#ffedd5" },
  fuel: { icon: "gas-station", iconColor: "#f97316", iconBg: "#ffedd5" },
  medical: { icon: "hospital-box-outline", iconColor: "#ef4444", iconBg: "#fee2e2" },
  health: { icon: "hospital-box-outline", iconColor: "#ef4444", iconBg: "#fee2e2" },
  medicine: { icon: "pill", iconColor: "#ef4444", iconBg: "#fee2e2" },
  insurance: { icon: "shield-check-outline", iconColor: "#10b981", iconBg: "#d1fae5" },
  gym: { icon: "dumbbell", iconColor: "#ec4899", iconBg: "#fce7f3" },
  entertainment: { icon: "television-play", iconColor: "#8b5cf6", iconBg: "#f3e8ff" },
  tv: { icon: "television-play", iconColor: "#8b5cf6", iconBg: "#f3e8ff" },
  netflix: { icon: "television-play", iconColor: "#8b5cf6", iconBg: "#f3e8ff" },
  streaming: { icon: "play-circle-outline", iconColor: "#8b5cf6", iconBg: "#f3e8ff" },
  subscription: { icon: "refresh", iconColor: "#8b5cf6", iconBg: "#f3e8ff" },
  savings: { icon: "piggy-bank-outline", iconColor: "#10b981", iconBg: "#d1fae5" },
  investment: { icon: "chart-line", iconColor: "#10b981", iconBg: "#d1fae5" },
  stock: { icon: "chart-line", iconColor: "#10b981", iconBg: "#d1fae5" },
  school: { icon: "school-outline", iconColor: "#f59e0b", iconBg: "#fef3c7" },
  education: { icon: "school-outline", iconColor: "#f59e0b", iconBg: "#fef3c7" },
  tuition: { icon: "school-outline", iconColor: "#f59e0b", iconBg: "#fef3c7" },
  child: { icon: "baby-carriage", iconColor: "#f59e0b", iconBg: "#fef3c7" },
  childcare: { icon: "baby-carriage", iconColor: "#f59e0b", iconBg: "#fef3c7" },
  pet: { icon: "paw-outline", iconColor: "#a855f7", iconBg: "#f3e8ff" },
  pets: { icon: "paw-outline", iconColor: "#a855f7", iconBg: "#f3e8ff" },
  clothing: { icon: "hanger", iconColor: "#6366f1", iconBg: "#e0e7ff" },
  clothes: { icon: "hanger", iconColor: "#6366f1", iconBg: "#e0e7ff" },
  shopping: { icon: "shopping-outline", iconColor: "#6366f1", iconBg: "#e0e7ff" },
  amazon: { icon: "shopping-outline", iconColor: "#6366f1", iconBg: "#e0e7ff" },
  groceries: { icon: "cart-outline", iconColor: "#22c55e", iconBg: "#dcfce7" },
  grocery: { icon: "cart-outline", iconColor: "#22c55e", iconBg: "#dcfce7" },
  car: { icon: "car", iconColor: "#3b82f6", iconBg: "#dbeafe" },
  vehicle: { icon: "car", iconColor: "#3b82f6", iconBg: "#dbeafe" },
  maintenance: { icon: "wrench-outline", iconColor: "#78716c", iconBg: "#f5f5f4" },
  repair: { icon: "wrench-outline", iconColor: "#78716c", iconBg: "#f5f5f4" },
  tax: { icon: "file-document-outline", iconColor: "#ef4444", iconBg: "#fee2e2" },
  taxes: { icon: "file-document-outline", iconColor: "#ef4444", iconBg: "#fee2e2" },
  gift: { icon: "gift-outline", iconColor: "#ec4899", iconBg: "#fce7f3" },
  donation: { icon: "heart-outline", iconColor: "#ef4444", iconBg: "#fee2e2" },
  charity: { icon: "heart-outline", iconColor: "#ef4444", iconBg: "#fee2e2" },
  vacation: { icon: "beach", iconColor: "#f59e0b", iconBg: "#fef3c7" },
  travel: { icon: "airplane", iconColor: "#3b82f6", iconBg: "#dbeafe" },
  hotel: { icon: "bed", iconColor: "#8b5cf6", iconBg: "#f3e8ff" },
  utilities: { icon: "lightning-bolt", iconColor: "#f59e0b", iconBg: "#fef3c7" },
  bill: { icon: "receipt", iconColor: "#f59e0b", iconBg: "#fef3c7" },
  bills: { icon: "receipt", iconColor: "#f59e0b", iconBg: "#fef3c7" },
};

export const SPLIT_ICON_FALLBACK = { icon: "circle-outline" as const, iconColor: "#6b7280", iconBg: "#f3f4f6" };

export function getSplitIcon(name: string) {
  const key = name.toLowerCase().trim();
  return SPLIT_ICON_MAP[key] ?? SPLIT_ICON_FALLBACK;
}
